lec05:
	ocamlbuild -use-ocamlfind -package qcheck,ppx_deriving.show lec05.native

hashtable:
	ocamlbuild -use-ocamlfind -package qcheck,qcstm,ppx_deriving.show hashtable.native

queue:
	ocamlbuild -use-ocamlfind -package qcheck,qcstm,ppx_deriving.show queuetest.native

clean:
	ocamlbuild -clean
