lec09:
	ocamlbuild -use-ocamlfind -package qcheck main.native
	ocamlbuild -use-ocamlfind -package qcheck stats.native
	ocamlbuild -use-ocamlfind -package qcheck typegen.cma

clean:
	ocamlbuild -clean

